# # Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
   push:
      branches: ["main"]

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

jobs:
  build:
    name: update html page
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          
      - name: Build environment
        shell: bash -l {0}
        run: |
          micromamba create --file environment.yml --name map-of-activities       
          
      - name: Execute Notebook
        shell: bash -l {0}
        run: |
          micromamba activate map-of-activities
          jupyter nbconvert --to notebook --execute map-of-activities.ipynb --output=map-of-activities-output.ipynb
          
      - name: Publish HTML
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/
          keep_files: true
